# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivopdf', '0002_auto_20180917_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopdf',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivopdfs', to='archivopdf.Autor'),
        ),
    ]
